branch-defaults:
  default:
    environment: dnew-env
    group_suffix: null
global:
  application_name: dnew
  default_ec2_keyname: chandan88
  default_platform: Python 2.7
  default_region: ap-southeast-1
  profile: eb-cli
  sc: null
